"""Initial migration with ApprovalFlow

Revision ID: 3d70066a9213
Revises: 
Create Date: 2025-12-23 18:19:01.915149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d70066a9213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='通知类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True, comment='会议描述'))
        batch_op.add_column(sa.Column('remind_minutes', sa.Integer(), nullable=True, comment='提前通知时间(分钟)，0表示不通知'))
        batch_op.add_column(sa.Column('is_notified', sa.Boolean(), nullable=True, comment='是否已通知'))

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=20), nullable=True, comment='等级: normal/important'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_minutes', sa.Integer(), nullable=True, comment='提前通知时间(分钟)，0表示不通知'))
        batch_op.add_column(sa.Column('is_notified', sa.Boolean(), nullable=True, comment='是否已通知'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('is_notified')
        batch_op.drop_column('remind_minutes')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('is_notified')
        batch_op.drop_column('remind_minutes')
        batch_op.drop_column('description')

    op.drop_table('system_notification')
    # ### end Alembic commands ###
